#!/bin/sh
# shellcheck disable=SC2029

# upload current repo using SCP to SSH remote
main () {
  [ $# -ne 1 ] && { usage && exit 2; }

  readonly currdir=$(dirname "$(readlink -f "$0")")
  readonly basedir="$(dirname "$(readlink -f "$(readlink -f "$currdir../")../")")"
  readonly reponame=$(basename "$basedir")
  readonly outfile="/tmp/$reponame.tgz"
  readonly remotedir="image/"
  readonly host="$1"

  trap clean SIGHUP SIGINT SIGTERM

  printf "creating %s\n" "$outfile"
  tar -czf "$outfile" -C "$basedir" .

  printf "creating %s:~/%s\n" "$host" "$remotedir"
  ssh "$host" "mkdir -p $remotedir"

  printf "copying %s to %s\n" "$outfile" "$host"
  scp "$outfile" "$host:$remotedir"

  clean
}

usage () {
  printf "usage: script/deploy <ssh-remote-name>\n"
}

clean () {
  printf "cleaning up %s\n" "$outfile"
  rm "$outfile"
  exit
}

main "$@"
